"use strict";

const RULES = [
  {
    id: "aws-access-key",
    name: "AWS Access Key ID",
    severity: "high",
    type: "secret",
    regex: /\bAKIA[0-9A-Z]{16}\b/g,
  },
  {
    id: "aws-secret-key",
    name: "AWS Secret Access Key",
    severity: "high",
    type: "secret",
    regex: /\baws_(?:secret_)?access_key\b[^A-Za-z0-9]{1,3}["']?([A-Za-z0-9\/+=]{40})\b/gi,
  },
  {
    id: "github-token",
    name: "GitHub Personal Access Token",
    severity: "high",
    type: "secret",
    regex: /\b(?:ghp_|gho_|ghu_|ghs_|ghr_)[A-Za-z0-9]{36,}\b/g,
  },
  {
    id: "github-pat-fine",
    name: "GitHub Fine-grained PAT",
    severity: "high",
    type: "secret",
    regex: /\bgithub_pat_[A-Za-z0-9_]{22,}\b/g,
  },
  {
    id: "gitlab-token",
    name: "GitLab Personal Access Token",
    severity: "high",
    type: "secret",
    regex: /\bglpat-[A-Za-z0-9_-]{20,}\b/g,
  },
  {
    id: "slack-token",
    name: "Slack Token",
    severity: "high",
    type: "secret",
    regex: /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/g,
  },
  {
    id: "stripe-live-key",
    name: "Stripe Live Secret Key",
    severity: "high",
    type: "secret",
    regex: /\b(?:sk|rk)_live_[0-9A-Za-z]{16,}\b/g,
  },
  {
    id: "stripe-test-key",
    name: "Stripe Test Secret Key",
    severity: "medium",
    type: "secret",
    regex: /\b(?:sk|rk)_test_[0-9A-Za-z]{16,}\b/g,
  },
  {
    id: "npm-token",
    name: "npm Access Token",
    severity: "high",
    type: "secret",
    regex: /\bnpm_[A-Za-z0-9]{36}\b/g,
  },
  {
    id: "google-api-key",
    name: "Google API Key",
    severity: "high",
    type: "secret",
    regex: /\bAIza[0-9A-Za-z_-]{35}\b/g,
  },
  {
    id: "twilio-api-key",
    name: "Twilio API Key",
    severity: "high",
    type: "secret",
    regex: /\bSK[0-9a-fA-F]{32}\b/g,
  },
  {
    id: "sendgrid-api-key",
    name: "SendGrid API Key",
    severity: "high",
    type: "secret",
    regex: /\bSG\.[0-9A-Za-z_-]{22}\.[0-9A-Za-z_-]{43}\b/g,
  },
  {
    id: "private-key",
    name: "Private Key Block",
    severity: "high",
    type: "secret",
    regex: /-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY[^]*?-----END (?:RSA |EC |DSA |OPENSSH |PGP )?PRIVATE KEY-----/g,
  },
  {
    id: "jwt",
    name: "JSON Web Token",
    severity: "medium",
    type: "secret",
    regex: /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/g,
  },
  {
    id: "connection-string",
    name: "Database Connection String",
    severity: "high",
    type: "secret",
    regex: /\b(?:postgres(?:ql)?|mysql|mongo(?:db)?|redis|amqp|mongodb\+srv|rediss):\/\/[^\s'"<>]+:[^\s'"<>@]+@[^\s'"<>]+/g,
  },
  {
    id: "aadhaar",
    name: "Aadhaar Number",
    severity: "high",
    type: "pii",
    regex: /(?<![0-9 -])[2-9]\d{3}[ -]?\d{4}[ -]?\d{4}(?![0-9 -])/g,
  },
  {
    id: "pan-india",
    name: "PAN (India)",
    severity: "medium",
    type: "pii",
    regex: /\b[A-Z]{5}\d{4}[A-Z]\b/g,
  },
  {
    id: "credit-card",
    name: "Credit Card Number",
    severity: "high",
    type: "pii",
    regex: /\b(?:\d[ -]*?){13,19}\b/g,
  },
  {
    id: "phone-india",
    name: "Indian Mobile Number",
    severity: "medium",
    type: "pii",
    regex: /(?<!\d)(?:\+91[- ]?)?[6-9]\d{9}(?!\d)/g,
  },
  {
    id: "email",
    name: "Email Address",
    severity: "medium",
    type: "pii",
    regex: /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g,
  },
  {
    id: "ip-address",
    name: "IP Address",
    severity: "low",
    type: "pii",
    regex: /\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b/g,
  },
  {
    id: "generic-credential",
    name: "Generic Credential Assignment",
    severity: "high",
    type: "secret",
    regex: /\b(?:api[_-]?key|apikey|secret|client[_-]?secret|access[_-]?token|auth[_-]?token|passwd|password)\b[^A-Za-z0-9]{0,3}["']?([A-Za-z0-9_\-.\/+]{16,})["']?/gi,
  },
];

module.exports = { RULES };
